name: comaslimpio
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.1.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  formz: ^0.8.0
  go_router: ^15.1.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Agregar el .env a los assets
  assets:
    - .env
    - assets/images/
    - assets/icons/
